django-project/src/fcc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-project/src/profiles/urls.py
from django.urls import path
from .views import my_profile_view


app_name = 'profiles'

urlpatterns = [
    path(
        '', my_profile_view, name='my'
    )
]

django-project/src/reports/urls.py
from django.urls import path
from .views import (create_report_view,
                    ReportListView,
                    ReportDetailView,
                    render_pdf_view,
                    UploadTemplateView,
                    csv_upload_view,
                    )

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('details/<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
    path('from_file/', UploadTemplateView.as_view(), name='from-file'),
]

django-project/src/sales/urls.py
from django.urls import path
from .views import (home_view, SalesListView, SaleDetailView,)
app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>/', SaleDetailView.as_view(), name='detail'),
]

django-project/src/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}" />

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <!-- jquery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" defer></script>

    <!-- Dropzone js -->
    <link rel="stylesheet" href="{% static 'dropzone.css' %}">
    <script src="{% static 'dropzone.js' %}" defer></script>

    <!-- Custom js & css -->
    <link rel="stylesheet" href="{% static 'style.css' %}"> {% block scripts %} {% endblock scripts %}

    <title>Report app | {% block title %}{% endblock title %}</title>
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container mt-3 mb-3">
        {% block content %} {% endblock content %}
    </div>

    <!-- Bootstrap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"></script>
</body>

</html>

django-project/src/templates/navbar.html
{% load static %}
{% url 'sales:home' as path_to_home %}
{% url 'sales:list' as path_to_sales %}
{% url 'reports:from-file' as path_to_from_file %}
{% url 'reports:main' as path_to_reports %}
{% url 'profiles:my' as path_to_my_profile %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href=""><img src="{% static 'logo.png' %}" class="logo-sm"></a>

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_home%}active{% endif %}"
                        href="{{path_to_home}}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_sales%}active{% endif %}"
                        href="{{path_to_sales}}">Sales</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_from_file%}active{% endif %}"
                        href="{{path_to_from_file}}">Add from file</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link {% if request.path == path_to_reports%}active{% endif %}"
                        href="{{path_to_reports}}">Reports</a>
                </li>
            </ul>
        </div>
        {% if request.user.is_authenticated %}
        <div class="nav-item dropdown">
            <div class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                <img src="{{request.user.profile.avatar.url}}" class="avatar-sm">&nbsp;{{request.user}}
            </div>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                <li><a class="dropdown-item {% if request.path == path_to_my_profile%}active{% endif %}"
                        href="{{path_to_my_profile}}">Profile</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
            </ul>
        </div>
        {% endif %}
    </div>
</nav>