django-project/src/fcc_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sales.urls', namespace='sales')),
    path('reports/', include('reports.urls', namespace='reports')),
    path('my_profile/', include('profiles.urls', namespace='profiles')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-project/src/reports/urls.py
from django.urls import path
from .views import (create_report_view,
                    ReportListView,
                    ReportDetailView,
                    render_pdf_view,
                    UploadTemplateView,
                    csv_upload_view,
                    )

app_name = 'reports'

urlpatterns = [
    path('', ReportListView.as_view(), name='main'),
    path('save/', create_report_view, name='create-report'),
    path('upload/', csv_upload_view, name='upload'),
    path('details/<pk>/', ReportDetailView.as_view(), name='detail'),
    path('<pk>/pdf/', render_pdf_view, name='pdf'),
    path('from_file/', UploadTemplateView.as_view(), name='from-file'),
]

django-project/src/sales/urls.py
from django.urls import path
from .views import (home_view, SalesListView, SaleDetailView,)
app_name = 'sales'

urlpatterns = [
    path('', home_view, name='home'),
    path('sales/', SalesListView.as_view(), name='list'),
    path('sales/<pk>/', SaleDetailView.as_view(), name='detail'),
]

django-project/src/reports/models.py
from django.db import models
from profiles.models import Profile
from django.urls import reverse

# Create your models here.


class Report(models.Model):
    name = models.CharField(max_length=120, null=True)
    image = models.ImageField(upload_to='reports', blank=True, null=True)
    remarks = models.TextField(null=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)

    def __str__(self):
        return str(self.name)

    def get_absolute_url(self):
        return reverse('reports:detail', kwargs={'pk': self.pk})

    class Meta:
        ordering = ('-created',)

django-project/src/reports/forms.py
from django import forms
from .models import Report


class ReportForm(forms.ModelForm):
    class Meta:
        model = Report
        fields = {'name', 'remarks'}

django-project/src/reports/views.py
from django.shortcuts import render, get_object_or_404
from profiles.models import Profile
from django.http import JsonResponse
from .utils import get_report_image
from .models import Report
from django.views.generic import ListView, DetailView, TemplateView
from django.conf import settings
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from sales.models import Position, Sale
from sales.models import CSV
from django.utils.dateparse import parse_date
from products.models import Product
from customers.models import Customer
import csv
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
# Create your views here.


class ReportListView(LoginRequiredMixin, ListView):
    model = Report
    template_name = 'reports/main.html'


class ReportDetailView(LoginRequiredMixin, DetailView):
    model = Report
    template_name = 'reports/detail.html'


class UploadTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'reports/from_file.html'


@login_required
def csv_upload_view(request):
    print('file is being sent  ')
    if request.method == 'POST':

        csv_file_name = request.FILES.get('file').name
        csv_file = request.FILES.get('file')
        obj, created = CSV.objects.get_or_create(file_name=csv_file_name)
        print(csv_file)
        print(type(csv_file_name))
        print(type(csv_file))
        print(csv_file_name)
        if created:
            obj.csv_file = csv_file
            obj.save()
        # csv_file = request.FILES.get('file').name
        # print(csv_file)
        # obj = CSV.objects.get_or_create(file_name=csv_file)
        # print(obj)
        # print(2)
            with open(obj.csv_file.path, 'r') as f:
                print(2)
                reader = csv.reader(f)
                print(2)
                reader.__next__()
                print(2)

                for row in reader:
                    print(row, type(row))
                    data = "".join(row)
                    data = data.split(";")
                    data.pop()
                    transaction_id = data[0]
                    product = data[2]
                    quantity = int(data[3])
                    customer = data[4]
                    date = parse_date(data[5])

                    try:
                        product_obj = Product.objects.get(name__iexact=product)
                    except Product.DoesNotExist:
                        product_obj = None

                    if product_obj is not None:
                        customer_obj, _ = Customer.objects.get_or_create(
                            name=customer)
                        salesman_obj = Profile.objects.get(user=request.user)
                        position_obj = Position.objects.create(
                            product=product_obj, quantity=quantity, created=date)
                        sale_obj = Sale.objects.get_or_create(
                            transaction_id=transaction_id, customer=customer_obj, salesman=salesman_obj, created=date)

                        sale_obj.positions.add(position_obj)
                        sale_obj.positions.add(position_obj)
                        sale_obj.save()
                return JsonResponse({'ex': False})
        else:
            return JsonResponse({'ex': True})
    return HttpResponse()


@login_required
def create_report_view(request):
    if request.is_ajax():
        name = request.POST.get('name')
        remarks = request.POST.get('remarks')
        image = request.POST.get('image')
        img = get_report_image(image)
        author = Profile.objects.get(user=request.user)
        # author = request.user.profile
        # print(author.__dict__)
        print(request.user.profile)
        print(Report)
        Report.objects.create(name=name, remarks=remarks,
                              image=img, author=author)
        return JsonResponse({'msg': 'send'})
    return JsonResponse({})


def render_pdf_view(request, pk):
    template_path = 'reports/pdf.html'
    object = get_object_or_404(Report, pk=pk)
    context = {'obj': object}

    # Create a Django response object, and specify content_type as pdf
    response = HttpResponse(content_type='application/pdf')
    # to download
    # response['Content-Disposition'] = 'attachment; filename="report.pdf"'
    # to view
    response['Content-Disposition'] = 'filename = "report.pdf"'
    # find the template and render it.
    template = get_template(template_path)
    html = template.render(context)

    # create a pdf
    pisa_status = pisa.CreatePDF(
        html, dest=response,)
    # if error then show some funy view
    if pisa_status.err:
        return HttpResponse('We had some errors <pre>' + html + '</pre>')
    return response

django-project/src/reports/templates/reports/detail.html
{% extends 'base.html' %}

{% block title%}
{{object.name}}
{% endblock title %}

{% block content %}

{% if object.image %}
<img src="{{object.image.url}}" class="img-fluid" alt="{{object.name}}">

{% endif %}
<h3>Remarks</h3>
<p>{{object.remarks}}</p>
<hr>
<p>author: {{object.author.user.username}}</p>
<p>created: {{object.created}}</p>
{% endblock content %}

django-project/src/reports/templates/reports/from_file.html
{% extends 'base.html' %}
{% load static %}
{% block scripts %}
<script src="{% static 'reports/upload.js' %}" defer>

</script>
{% endblock scripts %}
{% block title%}
Upload sales files
{% endblock title %}

{% block content %}
<h5>Upload your sales documents</h5>
<hr>
<div id="alert-box">

</div>
<form id="my-dropzone" class="dropzone dz">
    {% csrf_token %}
    <div class="fallback">
        <input name="file" type="file" multiple />
    </div>
</form>
{% endblock content %}

django-project/src/reports/templates/reports/main.html
{% extends 'base.html' %}

{% block title%}
reports
{% endblock title %}

{% block content %}

<br>
reports
<hr>
{% for obj in object_list %}

<div class="card mb-3" style="width: 18rem;">

    {% if obj.image %}
    <img src="{{obj.image.url}}" class="card-img-top" alt="{{obj.name}}">

    {% endif %}

    <div class="card-body">
        <h5 class="card-title">{{obj.name}}</h5>
        <p class="card-text">{{obj.remarks|truncatewords:2}}</p>
        <a href="{{obj.get_absolute_url}}" class="btn btn-primary">{{obj.name}}</a>

        <a href="{% url 'reports:pdf' obj.pk %}" class="btn btn-danger">PDF</a> <br>
    </div>
</div>

{% endfor %}
{% endblock content %}

django-project/src/reports/templates/reports/pdf.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">

    <title>PDF {{obj.name}}</title>
    <style>
        .image {
            width: 100%;
            height: auto;
        }
    </style>
</head>

<body>
    <h1>{{obj.name}}</h1>
    <hr>
    <img src="{{obj.image.path}}" class="image">
    <h3>Remarks</h3>
    <p>{{obj.remarks}}</p>
    <hr>
    <p>Author: <b>{{obj.author.user.username}}</b></p>

    <p>Created: <b>{{obj.created}}</b></p>
</body>

</html>